# Generated by Django 2.1 on 2019-11-28 17:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts', models.DateTimeField(verbose_name='start date')),
                ('ends', models.DateTimeField(verbose_name='end date')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('belongstoauction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebuy.Auction')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('condition', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='item_pictures/default.png', upload_to='item_pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutAuction', models.IntegerField(default=0)),
                ('fromUser', models.IntegerField(default=0)),
                ('toUser', models.IntegerField(default=0)),
                ('message', models.CharField(default=None, max_length=200)),
                ('response', models.CharField(default=None, max_length=200)),
                ('answered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('dob', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('bankNo', models.IntegerField(default=0)),
                ('phoneNo', models.IntegerField(default=0)),
                ('profileCreated', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='useritem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ebuy.User'),
        ),
        migrations.AddField(
            model_name='bid',
            name='belongstouser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebuy.User'),
        ),
        migrations.AddField(
            model_name='auction',
            name='auctionitem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ebuy.Item'),
        ),
    ]
