# Generated by Django 2.2.6 on 2019-11-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebuy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutAuction', models.IntegerField(default=0)),
                ('fromUser', models.IntegerField(default=0)),
                ('toUser', models.IntegerField(default=0)),
                ('message', models.CharField(default=None, max_length=200)),
                ('response', models.CharField(default=None, max_length=200)),
                ('answered', models.BooleanField(default=False)),
            ],
        ),
    ]
