# Generated by Django 2.2.6 on 2019-11-28 01:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ebuy', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
