# Generated by Django 2.1 on 2019-11-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebuy', '0004_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='item_pictures/default.png', upload_to='item_pictures'),
        ),
    ]
